# -*- mode: python ; coding: utf-8 -*-

from PyInstaller.utils.hooks import collect_submodules

photutils_submodules = collect_submodules('photutils')

a = Analysis(
    ['setiastrosuitelinux.py'],
    pathex=[],
    binaries=[],
    datas=[('/home/setiastroadmin/Desktop/cosmicclarity/env/lib/python3.8/site-packages/astroquery/CITATION', 'astroquery'), 
    ('/home/setiastroadmin/Desktop/cosmicclarity/env/lib/python3.8/site-packages/photutils/CITATION.rst', 'photutils'),
    ('wimilogo.png', '.'), ('wrench_icon.png', '.'), ('astrosuite.png', '.'), 
    ('LExtract.png', '.'),
    ('LInsert.png', '.'),
    ('slot1.png', '.'),
    ('slot0.png', '.'),
    ('slot2.png', '.'),
    ('slot3.png', '.'),
    ('slot4.png', '.'),
    ('slot5.png', '.'),
    ('slot6.png', '.'),
    ('slot7.png', '.'),
    ('slot8.png', '.'),
    ('slot9.png', '.'),    
    ('pixelmath.png', '.'),   
    ('histogram.png', '.'),     
    ('rgbcombo.png', '.'),
    ('cropicon.png', '.'),
    ('openfile.png', '.'),
    ('blaster.png', '.'),
    ('mosaic.png', '.'),
    ('graxpert.png','.'),
    ('hdr.png', '.'),
    ('invert.png', '.'),
    ('fliphorizontal.png', '.'),
    ('flipvertical.png', '.'),
    ('rotateclockwise.png', '.'),
    ('rotatecounterclockwise.png', '.'),
    ('rescale.png', '.'),
    ('staralign.png', '.'),
    ('maskcreate.png', '.'),
    ('maskapply.png', '.'),
    ('maskremove.png', '.'),    
    ('abeicon.png', '.'),
    ('undoicon.png', '.'),
    ('redoicon.png', '.'),
    ('rgbextract.png', '.'),
    ('copyslot.png', '.'),
    ('staradd.png', '.'),('starnet.png', '.'),('clahe.png', '.'),('morpho.png', '.'),('whitebalance.png', '.'),('neutral.png', '.'),('green.png', '.'),('celestial_catalog.csv', '.'), ('eye.png', '.'), ('disk.png', '.'), ('nuke.png', '.'), ('hubble.png', '.'), ('collage.png', '.'), ('annotated.png', '.'), ('colorwheel.png', '.'), ('font.png', '.'), ('spinner.gif', '.'), ('cvs.png', '.'), ('/home/setiastroadmin/Desktop/cosmicclarity/env/lib/python3.8/site-packages/astroquery/simbad/data', 'astroquery/simbad/data'), ('/home/setiastroadmin/Desktop/cosmicclarity/env/lib/python3.8/site-packages/astropy/CITATION', 'astropy'), ('imgs', 'imgs')],
    hiddenimports=photutils_submodules,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=['torch', 'torchvision'],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='setiastrosuitelinux',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=['astrosuite.png'],
)
